CREATE TABLE user_login_info (user_id int(10) NOT NULL AUTO_INCREMENT, user_name varchar(57) NOT NULL UNIQUE, user_email varchar(57) NOT NULL UNIQUE, user_pass text NOT NULL, PRIMARY KEY (user_id));
CREATE TABLE user_info (user_id int(10) NOT NULL, first_name varchar(57), last_name varchar(57), dob date, phone varchar(27), currency int(10), PRIMARY KEY (user_id));
CREATE TABLE post_details (pid int(10) NOT NULL, user_id int(10) NOT NULL, title text, description text, puser_name varchar(57), puser_pass text, post_cat int(10) NOT NULL, post_status varchar(17), post_time datetime NULL, price int(10), tag varchar(57), PRIMARY KEY (pid, user_id));
CREATE TABLE post_cat (cat_id int(10) NOT NULL AUTO_INCREMENT, cat_name varchar(57), PRIMARY KEY (cat_id));
CREATE TABLE admin_info (admin_id int(10) NOT NULL AUTO_INCREMENT, user_name varchar(57) NOT NULL UNIQUE, user_pass text, first_name varchar(57), last_name varchar(57), PRIMARY KEY (admin_id));
CREATE TABLE is_msg_created (msg_id int(10) NOT NULL, user_id int(10) NOT NULL, created_with_id int(10), PRIMARY KEY (msg_id, user_id));
CREATE TABLE inbox (msg_id int(10) NOT NULL, sender_id int(10) NOT NULL, reciever_id int(10) NOT NULL, msg text, msg_time datetime NULL, PRIMARY KEY (msg_id, sender_id, reciever_id));
CREATE TABLE transaction_history (tran_id int(10) NOT NULL AUTO_INCREMENT, seller_id int(10), buyer_id int(10), seller_post_id int(10), tran_time datetime NULL, pay_amount int(10), PRIMARY KEY (tran_id));
CREATE TABLE notification (id int(10) NOT NULL, user_id int(10) NOT NULL, content text NOT NULL, PRIMARY KEY (id, user_id));
CREATE TABLE payment_details (id int(10) NOT NULL, user_id int(10) NOT NULL, pay_amount int(10), pay_time datetime NULL, PRIMARY KEY (id, user_id));
CREATE TABLE report_admin (id int(10) NOT NULL, user_id int(10) NOT NULL, msg text, reported_user_id int(10) NOT NULL, reported_user_post_id int(10) NOT NULL, PRIMARY KEY (id, user_id));
ALTER TABLE user_info ADD INDEX FKuser_info867895 (user_id), ADD CONSTRAINT FKuser_info867895 FOREIGN KEY (user_id) REFERENCES user_login_info (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE post_details ADD INDEX FKpost_detai373973 (user_id), ADD CONSTRAINT FKpost_detai373973 FOREIGN KEY (user_id) REFERENCES user_login_info (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE post_details ADD INDEX FKpost_detai186947 (post_cat), ADD CONSTRAINT FKpost_detai186947 FOREIGN KEY (post_cat) REFERENCES post_cat (cat_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE is_msg_created ADD INDEX FKis_msg_cre373323 (user_id), ADD CONSTRAINT FKis_msg_cre373323 FOREIGN KEY (user_id) REFERENCES user_login_info (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE is_msg_created ADD INDEX FKis_msg_cre948411 (created_with_id), ADD CONSTRAINT FKis_msg_cre948411 FOREIGN KEY (created_with_id) REFERENCES user_login_info (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE inbox ADD INDEX FKinbox404537 (sender_id), ADD CONSTRAINT FKinbox404537 FOREIGN KEY (sender_id) REFERENCES user_login_info (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE inbox ADD INDEX FKinbox77771 (reciever_id), ADD CONSTRAINT FKinbox77771 FOREIGN KEY (reciever_id) REFERENCES user_login_info (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE transaction_history ADD INDEX FKtransactio952999 (seller_post_id, seller_id), ADD CONSTRAINT FKtransactio952999 FOREIGN KEY (seller_post_id, seller_id) REFERENCES post_details (pid, user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE transaction_history ADD INDEX FKtransactio337982 (buyer_id), ADD CONSTRAINT FKtransactio337982 FOREIGN KEY (buyer_id) REFERENCES user_login_info (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE notification ADD INDEX FKnotificati838894 (user_id), ADD CONSTRAINT FKnotificati838894 FOREIGN KEY (user_id) REFERENCES user_login_info (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE payment_details ADD INDEX FKpayment_de904192 (user_id), ADD CONSTRAINT FKpayment_de904192 FOREIGN KEY (user_id) REFERENCES user_login_info (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE report_admin ADD INDEX FKreport_adm902391 (user_id), ADD CONSTRAINT FKreport_adm902391 FOREIGN KEY (user_id) REFERENCES user_login_info (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE report_admin ADD INDEX FKreport_adm53944 (reported_user_post_id, reported_user_id), ADD CONSTRAINT FKreport_adm53944 FOREIGN KEY (reported_user_post_id, reported_user_id) REFERENCES post_details (pid, user_id) ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO `user_login_info`(`user_id`, `user_name`, `user_email`, `user_pass`) VALUES (1,"admin","admin","1234");
INSERT INTO `admin_info` VALUES (1,"admin","1234", "first admin", "last admin");